### ISSUE TITLE
game crash when using .viafabric

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaFabric#126]
```java
java.lang.NullPointerException: Ticking screen
	at io.netty.bootstrap.Bootstrap.checkAddress(Bootstrap.java:273)
	at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:150)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:132)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:113)
	at net.minecraft.class_913.method_3225(class_913.java:153)
	at net.minecraft.class_913.method_3223(class_913.java:34)
	at net.minecraft.class_913$1.method_5148(class_913.java:132)
	at net.minecraft.class_1432.method_5113(class_1432.java:368)
	at net.minecraft.class_913.method_3221(class_913.java:242)
	at net.minecraft.class_810.method_2804(class_810.java:114)
	at net.minecraft.class_669.method_2314(class_669.java:1513)
	at net.minecraft.class_669.method_2286(class_669.java:889)
	at net.minecraft.class_669.method_2247(class_669.java:325)
	at net.minecraft.client.main.Main.main(Main.java:124)
```

**Comment by creeper123123321** [comment]
need to analyse https://libraries.minecraft.net/com/mojang/netty/1.6/netty-1.6-sources.jar later

**Comment by florianreuth** [comment]
We've stopped updating the legacy branch due to having almost no use over the years, closing.
