### ISSUE TITLE
I used Travertine last version and Paper last version. This is a Bungee Error

### ISSUE THREAD

**Issue by iTito420** [ViaVersion/ViaFabric#133]
[17:48:40 INFO] [ViaVersion]: Loading 1.12 -> 1.13 mappings...
[17:48:40 INFO] [ViaVersion]: Loading 1.13 -> 1.13.2 mappings...
[17:48:40 INFO] [ViaVersion]: Loading 1.13.2 -> 1.14 mappings...
[17:48:40 INFO] [ViaVersion]: Loading 1.14 -> 1.15 mappings...
[17:48:40 INFO] [ViaVersion]: Loading 1.15 -> 1.16 mappings...
[17:48:40 ERROR] [ViaVersion]: Unable to inject ViaVersion, please post these details on our GitHub and ensure you're using a compatible server version.
[17:48:40 INFO] [ViaVersion]: Loading 1.16 -> 1.16.2 mappings...
[17:48:40 ERROR] [ViaVersion]: ViaVersion failed to inject:
[17:48:40 ERROR]: java.lang.reflect.InaccessibleObjectException: Unable to make private native java.lang.reflect.Field[] java.lang.Class.getDeclaredFields0(boolean) accessible: module java.base does not "opens java.lang" to unnamed module @3730f716
[17:48:40 ERROR]:       at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[17:48:40 ERROR]:       at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[17:48:40 ERROR]:       at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[17:48:40 ERROR]:       at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[17:48:40 ERROR]:       at us.myles.ViaVersion.bungee.platform.BungeeViaInjector.inject(BungeeViaInjector.java:35)
[17:48:40 ERROR]:       at us.myles.ViaVersion.ViaManager.init(ViaManager.java:64)
[17:48:40 ERROR]:       at us.myles.ViaVersion.BungeePlugin.onEnable(BungeePlugin.java:76)
[17:48:40 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315)
[17:48:40 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:298)
[17:48:40 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:80)
[17:48:40 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[17:48:40 INFO]: Enabled plugin ViaVersion version 3.2.1 by _MylesC, creeper123123321, Gerrygames, KennyTV, Matsv
[17:48:40 INFO]: Enabled plugin ViaRewind version 1.5.3 by Gerrygames

**Comment by iTito420** [comment]
Whhat is my error?

**Comment by KennyTV** [comment]
Update to -dev builds on https://ci.viaversion.com
