### ISSUE TITLE
fabric-resource-loader-v0 missing

### ISSUE THREAD

**Issue by NPC-Master3304** [ViaVersion/ViaFabric#166]
Okay this is really stupid to ask, but it says that the fabric resource loader is missing when I have the latest version of legacy fabric, viafabric, and viarewind. If this is a mod, I can't find it anywhere. I double checked to see if I was missing any required mods, but everything that it stated I had. I don't know if I'm doing something wrong or if this is a weird bug.

```
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-resource-loader-v0, any version.
Unmet dependency listing:
	 - Mod 'ViaFabric' (viafabric) 0.3.1-SNAPSHOT+build-705.1-mc-1.8 requires any version of fabric-resource-loader-v0, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-resource-loader-v0, any version.
Unmet dependency listing:
	 - Mod 'ViaFabric' (viafabric) 0.3.1-SNAPSHOT+build-705.1-mc-1.8 requires any version of fabric-resource-loader-v0, which is missing!
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 11 more
```

**Comment by creeper123123321** [comment]
Try downgrading from [Boogie's Griefed API. DONT USE](https://www.curseforge.com/minecraft/mc-mods/legacy-fabric-api/files/3540451) to [0.10.0](https://www.curseforge.com/minecraft/mc-mods/legacy-fabric-api/files/3129156)

**Comment by creeper123123321** [comment]
ViaFabric is outdated

**Comment by NPC-Master3304** [comment]
```
[16:56:17] [main/INFO]: Loading Minecraft 1.8.9 with Fabric Loader 0.12.12
[16:56:17] [main/WARN]: Warnings were found!
 - Mod 'ViaRewind' (viarewind) 2.0.2 recommends any version of viabackwards, which is missing!
	 - You should install any version of viabackwards for the optimal experience.
[16:56:17] [main/INFO]: Loading 26 mods:
	- fabric 0.10.0
	- fabric-api-base 0.1.4+nogit via fabric
	- fabric-armor-api-v1 1.0.2+nogit via fabric
	- fabric-commands-v0 1.1.0+nogit via fabric
	- fabric-commands-v1 0.1.0+nogit via fabric
	- fabric-content-registries-v1 1.3.0+nogit via fabric
	- fabric-crash-report-info-v1 0.1.2+nogit via fabric
	- fabric-events-interaction-v0 0.4.4+nogit via fabric
	- fabric-events-lifecycle-v0 0.2.1+nogit via fabric
	- fabric-gamerule-api-v1 1.0.1+nogit via fabric
	- fabric-item-groups-v0 0.1.2+nogit via fabric
	- fabric-key-binding-api-v1 1.0.1+nogit via fabric
	- fabric-lifecycle-events-v1 1.1.2+nogit via fabric
	- fabric-networking-blockentity-v0 0.2.0+nogit via fabric
	- fabric-networking-v0 0.2.0+nogit via fabric
	- fabric-object-builder-api-v1 1.0.2+nogit via fabric
	- fabric-recipes-v1 1.1.0+nogit via fabric
	- fabric-rendering-v1 1.0.2+nogit via fabric
	- fabric-resource-loader-v0 0.3.0+nogit via fabric
	- fabricloader 0.12.12
	- java 17
	- minecraft 1.8.9
	- org_yaml_snakeyaml 1.29 via viafabric
	- viafabric 0.4.5+244-main
	- viarewind 2.0.2
	- viaversion 4.1.1-SNAPSHOT via viafabric
[16:56:18] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/D:/Geek%20Squad%20Data%20Backup%203-4-14/Desktop2018/NPC/MultiMC/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[16:56:19] [main/WARN]: Error loading class: net/minecraft/class_1581 (java.lang.ClassNotFoundException: net/minecraft/class_1581)
[16:56:19] [main/WARN]: @Mixin target net.minecraft.class_1581 was not found fabric-commands-v0.mixins.json:MixinCommandRegistry
[16:56:19] [main/WARN]: Error loading class: net/minecraft/class_360 (java.lang.ClassNotFoundException: net/minecraft/class_360)
[16:56:19] [main/WARN]: @Mixin target net.minecraft.class_360 was not found fabric-content-registries-v1.mixins.json:MixinFurnaceBlockEntity
[16:56:19] [main/WARN]: Error loading class: net/minecraft/class_1963 (java.lang.ClassNotFoundException: net/minecraft/class_1963)
[16:56:19] [main/WARN]: @Mixin target net.minecraft.class_1963 was not found fabric-content-registries-v1.mixins.json:MixinPlayerEntity
[16:56:19] [main/WARN]: Error loading class: net/minecraft/class_1399 (java.lang.ClassNotFoundException: net/minecraft/class_1399)
[16:56:19] [main/WARN]: @Mixin target net.minecraft.class_1399 was not found fabric-content-registries-v1.mixins.json:MutableRegistryAccessor
[16:56:19] [main/WARN]: Error loading class: net/minecraft/class_1393 (java.lang.ClassNotFoundException: net/minecraft/class_1393)
[16:56:19] [main/WARN]: @Mixin target net.minecraft.class_1393 was not found fabric-content-registries-v1.mixins.json:SimpleRegistryAccessor
[16:56:19] [main/WARN]: Error loading class: net/minecraft/class_825 (java.lang.ClassNotFoundException: net/minecraft/class_825)
[16:56:19] [main/WARN]: @Mixin target net.minecraft.class_825 was not found fabric-crash-report-info-v1.mixins.json:MixinCrashReport
[16:56:19] [main/WARN]: Error loading class: net/minecraft/class_669 (java.lang.ClassNotFoundException: net/minecraft/class_669)
[16:56:19] [main/WARN]: @Mixin target net.minecraft.class_669 was not found fabric-events-interaction-v0.mixins.json:MixinMinecraftClient
[16:56:19] [main/WARN]: Error loading class: net/minecraft/class_95 (java.lang.ClassNotFoundException: net/minecraft/class_95)
[16:56:19] [main/WARN]: @Mixin target net.minecraft.class_95 was not found fabric-gamerule-api-v1.mixins.json:MixinGameRules
[16:56:19] [main/WARN]: Error loading class: net/minecraft/class_2029 (java.lang.ClassNotFoundException: net/minecraft/class_2029)
[16:56:19] [main/WARN]: @Mixin target net.minecraft.class_2029 was not found fabric-item-groups-v0.mixins.json:MixinItemGroup
[16:56:19] [main/WARN]: Error loading class: net/minecraft/class_2029 (java.lang.ClassNotFoundException: net/minecraft/class_2029)
[16:56:19] [main/WARN]: @Mixin target net.minecraft.class_2029 was not found fabric-item-groups-v0.mixins.json:client.MixinItemGroup
[16:56:19] [main/WARN]: Error loading class: net/minecraft/class_666 (java.lang.ClassNotFoundException: net/minecraft/class_666)
[16:56:19] [main/WARN]: @Mixin target net.minecraft.class_666 was not found fabric-key-binding-api-v1.mixins.json:KeyCodeAccessor
[16:56:19] [main/WARN]: Error loading class: net/minecraft/class_671 (java.lang.ClassNotFoundException: net/minecraft/class_671)
[16:56:19] [main/WARN]: @Mixin target net.minecraft.class_671 was not found fabric-key-binding-api-v1.mixins.json:MixinGameOptions
[16:56:19] [main/WARN]: Error loading class: net/minecraft/class_1745 (java.lang.ClassNotFoundException: net/minecraft/class_1745)
[16:56:19] [main/WARN]: @Mixin target net.minecraft.class_1745 was not found fabric-lifecycle-events-v1.mixins.json:MixinEntity
[16:56:19] [main/WARN]: Error loading class: net/minecraft/class_1890 (java.lang.ClassNotFoundException: net/minecraft/class_1890)
[16:56:19] [main/WARN]: @Mixin target net.minecraft.class_1890 was not found fabric-lifecycle-events-v1.mixins.json:MixinLightningBoltEntity
[16:56:19] [main/ERROR]: Mixin prepare for mod fabric-lifecycle-events-v1 failed preparing MixinServerPlayNetworkHandler in fabric-lifecycle-events-v1.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Mixin target type mismatch: net.minecraft.class_1643 is an interface in org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard@7e242b4d
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Mixin target type mismatch: net.minecraft.class_1643 is an interface in org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard@7e242b4d
	at org.spongepowered.asm.mixin.transformer.MixinInfo$SubType.validateTarget(MixinInfo.java:553) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1027) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1008) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:896) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:869) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-loader-0.12.12.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:606) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.12.12.jar:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

```

I tried that before, but it just crashes. I don't see any viafabric version that's beyond 0.3.1 that supports 1.8.9.
