### ISSUE TITLE
legacy fabric API crashing

### ISSUE THREAD

**Issue by NPC-Master3304** [ViaVersion/ViaFabric#169]
Legacy intermediary was recently changed, try deleting .fabric in your .minecraft directory

Also, legacy fabric API needs to be updated to the new intermediary

_Originally posted by @creeper123123321 in https://github.com/ViaVersion/ViaFabric/issues/167#issuecomment-1016243280_

```
MultiMC` version: 0.6.14-3001


Launched instance in online mode

authserver.mojang.com resolves to:
    [65.8.46.71]

session.minecraft.net resolves to:
    [3.223.61.237, 52.206.61.151, 3.209.165.60]

textures.minecraft.net resolves to:
    [54.230.15.115, 54.230.15.74, 54.230.15.75, 54.230.15.58]

api.mojang.com resolves to:
    [52.84.55.158]


Minecraft folder is:
D:/XXXX/XXXX/NPC/MultiMC/instances/mmc_legacy_fabric_1.8.9/.minecraft


Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe


Checking Java version...
Java is version 17.0.1, using 64-bit architecture, from Oracle Corporation.


Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  D:/XXXX/XXXX/NPC/MultiMC/instances/mmc_legacy_fabric_1.8.9/natives

Libraries:
  D:/XXXX/XXXX/NPC/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/com/mojang/realms/1.7.59/realms-1.7.59.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/net/fabricmc/intermediary/1.8.9/intermediary-1.8.9.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/net/fabricmc/fabric-loader/0.12.12/fabric-loader-0.12.12.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/net/fabricmc/tiny-remapper/0.6.0/tiny-remapper-0.6.0.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/net/fabricmc/access-widener/2.0.1/access-widener-2.0.1.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/net/fabricmc/fabric-loader-1.8.9/0.8.7+build.202006122116/fabric-loader-1.8.9-0.8.7+build.202006122116.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/com/mojang/minecraft/1.8.9/minecraft-1.8.9-client.jar

Native libraries:
  D:/XXXX/XXXX/NPC/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-windows-64.jar
  D:/XXXX/XXXX/NPC/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [✔️] legacy-fabric-api-1.1.0+1.8.9
  [❌] viafabric-0.4.5+244-main.jar (disabled)
  [❌] ViaRewind-2.0.2.jar (disabled)
  [❌] ViaVersion-4.1.1.jar (disabled)

Params:
  --username  --version MultiMC5 --gameDir D:/XXXX/XXXX/NPC/MultiMC/instances/mmc_legacy_fabric_1.8.9/.minecraft --assetsDir D:/XXXX/XXXX/NPC/MultiMC/assets --assetIndex 1.8 --uuid  --accessToken  --userProperties  --userType 

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 11436


Using onesix launcher.

[11:36:27] [main/INFO]: Loading Minecraft 1.8.9 with Fabric Loader 0.12.12
[11:36:27] [main/INFO]: Loading 14 mods:
	- fabric-gamerule-api-v1 1.0.0+dd1d9f8d39 via legacy-fabric-api
	- fabricloader 0.12.12
	- java 17
	- legacy-fabric-api 1.1.0+1.8.9
	- legacy-fabric-api-base 1.0.0+1e58a10239 via legacy-fabric-api
	- legacy-fabric-crash-report-info-v1 1.0.0+bb775ea439 via legacy-fabric-api
	- legacy-fabric-entity-events-v1 1.0.0+1e58a10239 via legacy-fabric-api
	- legacy-fabric-keybinding-api-v1 1.0.0+1e58a10239 via legacy-fabric-api
	- legacy-fabric-lifecycle-events-v1 1.0.0+1e58a10239 via legacy-fabric-api
	- legacy-fabric-networking-api-v1 1.0.0+274de2e039 via legacy-fabric-api
	- legacy-fabric-rendering-api-v1 1.0.0+1e58a10239 via legacy-fabric-api
	- legacy-fabric-resource-loader-v1 1.0.0+1e58a10239 via legacy-fabric-api
	- legacy-fabric-vanilla-command-api-v1 1.0.0+dd1d9f8d39 via legacy-fabric-api
	- minecraft 1.8.9
[11:36:27] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/D:/Geek%20Squad%20Data%20Backup%203-4-14/Desktop2018/NPC/MultiMC/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[11:36:28] [main/WARN]: Error loading class: net/minecraft/class_95 (java.lang.ClassNotFoundException: net/minecraft/class_95)
[11:36:28] [main/WARN]: @Mixin target net.minecraft.class_95 was not found legacy-fabric-gamerule-api-v1.mixins.json:GameRulesMixin
[11:36:28] [main/WARN]: Error loading class: net/minecraft/class_825 (java.lang.ClassNotFoundException: net/minecraft/class_825)
[11:36:28] [main/WARN]: @Mixin target net.minecraft.class_825 was not found legacy-fabric-crash-report-info-v1.mixins.json:CrashReportMixin
[11:36:28] [main/WARN]: Error loading class: net/minecraft/class_1745 (java.lang.ClassNotFoundException: net/minecraft/class_1745)
[11:36:28] [main/WARN]: @Mixin target net.minecraft.class_1745 was not found legacy-fabric-entity-events-v1.mixins.json:EntityMixin
[11:36:28] [main/WARN]: Error loading class: net/minecraft/class_671 (java.lang.ClassNotFoundException: net/minecraft/class_671)
[11:36:28] [main/WARN]: @Mixin target net.minecraft.class_671 was not found legacy-fabric-keybinding-api-v1.mixins.json:GameOptionsMixin
[11:36:28] [main/WARN]: Error loading class: net/minecraft/class_669 (java.lang.ClassNotFoundException: net/minecraft/class_669)
[11:36:28] [main/WARN]: @Mixin target net.minecraft.class_669 was not found legacy-fabric-lifecycle-events-v1.mixins.json:client.MinecraftClientMixin
[11:36:28] [main/WARN]: Error loading class: net/minecraft/class_1630 (java.lang.ClassNotFoundException: net/minecraft/class_1630)
[11:36:28] [main/WARN]: @Mixin target net.minecraft.class_1630 was not found legacy-fabric-networking-api-v1.mixins.json:EntityTrackerAccessor
[11:36:28] [main/ERROR]: Mixin prepare for mod legacy-fabric-networking-api-v1 failed preparing ServerPlayNetworkHandlerMixin in legacy-fabric-networking-api-v1.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Mixin target type mismatch: net.minecraft.class_1643 is an interface in org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard@40e10ff8
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Mixin target type mismatch: net.minecraft.class_1643 is an interface in org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard@40e10ff8
	at org.spongepowered.asm.mixin.transformer.MixinInfo$SubType.validateTarget(MixinInfo.java:553) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1027) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1008) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:896) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:869) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-loader-0.12.12.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:606) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.12.12.jar:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.client.main.Main failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:606)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	... 8 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [legacy-fabric-networking-api-v1.mixins.json:ServerPlayNetworkHandlerMixin] from phase [DEFAULT] in config [legacy-fabric-networking-api-v1.mixins.json] from mod [legacy-fabric-networking-api-v1] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Mixin target type mismatch: net.minecraft.class_1643 is an interface in org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard@40e10ff8
	at org.spongepowered.asm.mixin.transformer.MixinInfo$SubType.validateTarget(MixinInfo.java:553)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1027)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1008)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:896)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:869)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 20 more
Exiting with -1
Process exited with code -1.
```

legacy fabric api crashes?

**Comment by creeper123123321** [comment]
Don't use legacy fabric API, use this https://maven.rewovenmc.tk/net/legacyfabric/legacy-fabric-api/rewoven-resource-loader-v1/1.0.0+7af88e5b39/rewoven-resource-loader-v1-1.0.0+7af88e5b39.jar

**Comment by NPC-Master3304** [comment]
> Don't use legacy fabric API, use this https://maven.rewovenmc.tk/net/legacyfabric/legacy-fabric-api/rewoven-resource-loader-v1/1.0.0+7af88e5b39/rewoven-resource-loader-v1-1.0.0+7af88e5b39.jar

oh alr thank u. do u mind linking the original src so i know where to get updates from?
