### ISSUE TITLE
same crash appears with the legacy rewoven resource loader

### ISSUE THREAD

**Issue by NPC-Master3304** [ViaVersion/ViaFabric#170]
Don't use legacy fabric API, use this https://maven.rewovenmc.tk/net/legacyfabric/legacy-fabric-api/rewoven-resource-loader-v1/1.0.0+7af88e5b39/rewoven-resource-loader-v1-1.0.0+7af88e5b39.jar

_Originally posted by @creeper123123321 in https://github.com/ViaVersion/ViaFabric/issues/169#issuecomment-1016870397_
> Don't use legacy fabric API, use this https://maven.rewovenmc.tk/net/legacyfabric/legacy-fabric-api/rewoven-resource-loader-v1/1.0.0+7af88e5b39/rewoven-resource-loader-v1-1.0.0+7af88e5b39.jar

```
Mods:
  [❌] legacy-fabric-api-1.1.0+1.8.9.jar (disabled)
  [✔️] rewoven-resource-loader-v1-1.0.0+7af88e5b39
  [✔️] ViaFabric-0.3.1-SNAPSHOT+build-705.1-mc-1.8
  [✔️] ViaRewind-2.0.2
  [✔️] ViaVersion-4.1.1

Params:
  --username  --version MultiMC5 --gameDir D:/Geek Squad Data Backup 3-4-14/Desktop2018/NPC/MultiMC/instances/mmc_legacy_fabric_1.8.9/.minecraft --assetsDir D:/Geek Squad Data Backup 3-4-14/Desktop2018/NPC/MultiMC/assets --assetIndex 1.8 --uuid  --accessToken  --userProperties  --userType 

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 24092


Using onesix launcher.

[16:28:26] [main/INFO]: Loading Minecraft 1.8.9 with Fabric Loader 0.12.12
[16:28:26] [main/WARN]: Mod resolution failed
[16:28:26] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE viafabric 0.3.1-SNAPSHOT+build-705.1-mc-1.8 {depends fabric-resource-loader-v0 @ [*]}, ROOT_FORCELOAD_SINGLE viafabric 0.3.1-SNAPSHOT+build-705.1-mc-1.8]
[16:28:26] [main/INFO]: Reason: [HARD_DEP viafabric 0.3.1-SNAPSHOT+build-705.1-mc-1.8 {depends fabric-resource-loader-v0 @ [*]}]
[16:28:26] [main/INFO]: Fix: add [add:fabric-resource-loader-v0 1 ([(-?,?)])], remove [], replace []
[16:28:26] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-resource-loader-v0, any version.
Unmet dependency listing:
	 - Mod 'ViaFabric' (viafabric) 0.3.1-SNAPSHOT+build-705.1-mc-1.8 requires any version of fabric-resource-loader-v0, which is missing!
Inactive mods:
	 - mod 'ViaVersion' (viaversion) 3.2.1, reason: newer version active
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.12.12.jar:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-resource-loader-v0, any version.
Unmet dependency listing:
	 - Mod 'ViaFabric' (viafabric) 0.3.1-SNAPSHOT+build-705.1-mc-1.8 requires any version of fabric-resource-loader-v0, which is missing!
Inactive mods:
	 - mod 'ViaVersion' (viaversion) 3.2.1, reason: newer version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187) ~[fabric-loader-0.12.12.jar:?]
	... 11 more
Process exited with code 1.
```

**Comment by creeper123123321** [comment]
Update viafabric

**Comment by NPC-Master3304** [comment]
> Update viafabric

but there is no later viafabric version for 1.8.9. im so confused

**Comment by NPC-Master3304** [comment]
> Update viafabric

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 1/19/22, 11:39 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'viafabric'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_1600.method_2921(class_1600.java:349)
	at net.minecraft.class_1600.method_5580(class_1600.java:310)
	at net.minecraft.client.main.Main.main(Main.java:124)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.IllegalStateException: ViaFabric sub-mod didn't load correctly. Check if required dependencies are installed
	at com.viaversion.fabric.common.ViaFabric.onInitialize(ViaFabric.java:12)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 20 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_1600.method_2921(class_1600.java:349)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_1600.method_5580(class_1600.java:310)
	at net.minecraft.client.main.Main.main(Main.java:124)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 411343200 bytes (392 MB) / 536870912 bytes (512 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: ~~ERROR~~ NullPointerException: Cannot read field "field_10330" because "this.field_10318.field_3823" is null
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: Cannot read field "field_7670" because "this.field_5044.field_3823" is null
	Current Language: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_1666.method_5942()" because the return value of "net.minecraft.class_1600.method_5579(net.minecraft.class_1600)" is null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
```

this is what happens when i use the latest version even though it says 1.18. there is no later viafabric version for 1.8.9 unless ur talking about a developer build, then do u mind sending me that?

**Comment by creeper123123321** [comment]
https://www.curseforge.com/minecraft/mc-mods/viafabric/files/3613305

**Comment by buzzcoding** [comment]
ViaFabric versions are released under the latest Minecraft version they support. The latest one supports 1.8.x-1.18.x.

**Comment by NPC-Master3304** [comment]
oh I didn't see that alpha version. thank you. one thing though, when i attempt to connect to 1.18.1 servers in 1.8.9 with viarewind and viabackwards, it doesnt allow me to connect. is that suppose to happen or?

**Comment by Kichura** [comment]
For normal compatibility; Only viafabric is required to join older servers,

However if you wanted to connect to a newer server then viabackwards (+ viarewind if on 1.8.9) is required along for forward conpatibility. (Latest builds of via* would be strongly advised)

**Comment by creeper123123321** [comment]
Legacy Fabric was fixed
