### ISSUE TITLE
Crash upon startup, appears to be an issue with mixins

### ISSUE THREAD

**Issue by BookWyrm114** [ViaVersion/ViaFabric#178]
**Describe the bug, provide any errors**
[17:33:28] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config mixins.viafabric118.address.json for mod viafabric-mc118
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.13.3.jar:?]
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config mixins.viafabric118.address.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-loader-0.13.3.jar:?]
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'mixins.viafabric118.address.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-loader-0.13.3.jar:?]
	... 3 more

**Is this happening specifically on ViaFabric?**
yes

**How can we reproduce it?**
try using viafabric with the latest version of fabric and fabricAPI

**Expected behaviour**
it would start

**Comment by BookWyrm114** [comment]
nevermind, this issue stopped when I installed viarewind
