### ISSUE TITLE
Unable to join from 1.20.1 to 1.19.4

### ISSUE THREAD

**Issue by silverfox0000** [ViaVersion/ViaFabric#268]
### `/viaversion dump` Output

https://dump.viaversion.com/9082b57404f0944e97487ad52c6d57097047975b2743f09965950f2c5051bdcd

### Console Error

```
No error
```

### Bug Description

Unable to join 1.19.4 server from 1.20.1
```
[16:15:16] [Render thread/ERROR]: Received unknown remote registry entries from server
[16:15:16] [Render thread/ERROR]: Registry entry (minecraft:pottery_shard_archer) is missing from local registry (minecraft:item)
[16:15:16] [Render thread/ERROR]: Registry entry (minecraft:pottery_shard_prize) is missing from local registry (minecraft:item)
[16:15:16] [Render thread/ERROR]: Registry entry (minecraft:pottery_shard_arms_up) is missing from local registry (minecraft:item)
[16:15:16] [Render thread/ERROR]: Registry entry (minecraft:pottery_shard_skull) is missing from local registry (minecraft:item)
[16:15:16] [Render thread/ERROR]: Registry entry (minecraft:suspicious_sand) is missing from local registry (minecraft:block_entity_type)
[16:15:16] [Render thread/ERROR]: Registry remapping failed!
net.fabricmc.fabric.impl.registry.sync.RemapException: Received 5 registry entries that are unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

minecraft

	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.checkRemoteRemap(RegistrySyncManager.java:388) ~[fabric-registry-sync-v0-2.2.6+b3afc78b77-83d298b0153c5de0.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:284) ~[fabric-registry-sync-v0-2.2.6+b3afc78b77-83d298b0153c5de0.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:118) ~[fabric-registry-sync-v0-2.2.6+b3afc78b77-83d298b0153c5de0.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
```

### Steps to Reproduce

1. Start server 1.19.4
2. Install ViaFabric And ViaBackwards from CI 
3. Attempt to connect the server

### Expected Behavior

Join to the server

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by silverfox0000** [comment]
Yep, error caused mod Brewery by Patbox
