### ISSUE TITLE
viafabric-0.4.11+43-dev won't start on 1.20.1 server

### ISSUE THREAD

**Issue by Xampa5** [ViaVersion/ViaFabric#280]
### `/viaversion dump` Output

no-dump.wontstart

### Console Error

[main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'viafabric'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.24.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.14.24-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.IllegalStateException: ViaFabric sub-mod didn't load correctly. Check if required dependencies are installed
        at com.viaversion.fabric.common.ViaFabric.onInitialize(ViaFabric.java:12) ~[viafabric-0.4.11+43-dev.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
        ... 7 more

### Bug Description

viafabric-0.4.11+43-dev is tagged as compatible with minecraft 1.20.1 on Modrinth but the fabric.mod.json _depends_ does not includes 1.20.1. 
https://modrinth.com/mod/viafabric/versions?g=1.20.1

**In case it's merely a mc version tag issue on Modrinth disregard this issue.**

After editing fabric.mod.json to accept 1.20.1 the server won't start and I get the error pasted above

### Steps to Reproduce

edit viafabric-0.4.11+43-dev's fabric.mod.json to accept minecraft 1.20.1
put viafabric-0.4.11+43-dev and fabric-api-0.90.7+1.20.1 as the only mods in the mod folder
start server

### Expected Behavior

server starts

### Additional Server Info

using fabric-api-0.90.7+1.20.1

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [ ] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [ ] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by FlorianMichael** [comment]
Minecraft 1.20.1 isn't supported anymore, you can't just edit the fabric mod json and except the mod to run since Minecraft's code has changed in these versions, use either the ViaProxy or Via As a service.

**Comment by Kichura** [comment]
Update: 1.20.1 is supported as it is now an LTS version. *(for now)*
