### ISSUE TITLE
DecoderException

### ISSUE THREAD

**Issue by swat1x** [ViaVersion/ViaFabric#295]
### `/viaversion dump` Output

i even can't join server

### Console Error

[04:27:07] [Netty Client IO #2/WARN]: ERROR IN Protocol1_20_2To1_20 IN REMAP OF CHUNK_DATA (0x24)
[04:27:07] [Netty Client IO #2/ERROR]: Packet error
io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: CHUNK_DATA, Type: ChunkType1_18, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.protocol1_20_2to1_20.rewriter.BlockItemPacketRewriter1_20_2$$Lambda$5419/0x0000019901bbc818, Packet ID: 37
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: CHUNK_DATA, Type: ChunkType1_18, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.protocol1_20_2to1_20.rewriter.BlockItemPacketRewriter1_20_2$$Lambda$5419/0x0000019901bbc818, Packet ID: 37
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(5117) + length(8) exceeds writerIndex(5122): PooledUnsafeDirectByteBuf(ridx: 5117, widx: 5122, cap: 5122)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.97.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:835) ~[netty-buffer-4.1.97.Final.jar:?]
	at com.viaversion.viaversion.api.type.types.LongArrayType.read(LongArrayType.java:39) ~[viaversion-4.10.0-23w51b-SNAPSHOT-e624d400c91c9134.jar:?]
	at com.viaversion.viaversion.api.type.types.LongArrayType.read(LongArrayType.java:28) ~[viaversion-4.10.0-23w51b-SNAPSHOT-e624d400c91c9134.jar:?]
	at com.viaversion.viaversion.api.type.types.chunk.PaletteType1_18.read(PaletteType1_18.java:51) ~[viaversion-4.10.0-23w51b-SNAPSHOT-e624d400c91c9134.jar:?]
	at com.viaversion.viaversion.api.type.types.chunk.ChunkSectionType1_18.read(ChunkSectionType1_18.java:47) ~[viaversion-4.10.0-23w51b-SNAPSHOT-e624d400c91c9134.jar:?]
	at com.viaversion.viaversion.api.type.types.chunk.ChunkType1_18.read(ChunkType1_18.java:58) ~[viaversion-4.10.0-23w51b-SNAPSHOT-e624d400c91c9134.jar:?]
	at com.viaversion.viaversion.api.type.types.chunk.ChunkType1_18.read(ChunkType1_18.java:36) ~[viaversion-4.10.0-23w51b-SNAPSHOT-e624d400c91c9134.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:142) ~[viaversion-4.10.0-23w51b-SNAPSHOT-e624d400c91c9134.jar:?]
	at com.viaversion.viaversion.protocols.protocol1_20_2to1_20.rewriter.BlockItemPacketRewriter1_20_2.lambda$registerPackets$4(BlockItemPacketRewriter1_20_2.java:96) ~[viaversion-4.10.0-23w51b-SNAPSHOT-e624d400c91c9134.jar:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) ~[viaversion-4.10.0-23w51b-SNAPSHOT-e624d400c91c9134.jar:?]
	at com.viaversion.viaversion.protocols.protocol1_20_2to1_20.Protocol1_20_2To1_20.transform(Protocol1_20_2To1_20.java:207) ~[viaversion-4.10.0-23w51b-SNAPSHOT-e624d400c91c9134.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423) ~[viaversion-4.10.0-23w51b-SNAPSHOT-e624d400c91c9134.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407) ~[viaversion-4.10.0-23w51b-SNAPSHOT-e624d400c91c9134.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[viaversion-4.10.0-23w51b-SNAPSHOT-e624d400c91c9134.jar:?]
	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:115) ~[viaversion-4.10.0-23w51b-SNAPSHOT-e624d400c91c9134.jar:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[viaversion-4.10.0-23w51b-SNAPSHOT-e624d400c91c9134.jar:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[viaversion-4.10.0-23w51b-SNAPSHOT-e624d400c91c9134.jar:?]
	at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:248) ~[viaversion-4.10.0-23w51b-SNAPSHOT-e624d400c91c9134.jar:?]
	at com.viaversion.fabric.common.handler.FabricDecodeHandler.decode(FabricDecodeHandler.java:40) ~[ViaFabric-0.4.12+55-dev.jar:?]
	at com.viaversion.fabric.common.handler.FabricDecodeHandler.decode(FabricDecodeHandler.java:17) ~[ViaFabric-0.4.12+55-dev.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[netty-codec-4.1.97.Final.jar:?]
	... 31 more
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: CHUNK_DATA, Type: ChunkType1_18, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.protocol1_20_2to1_20.rewriter.BlockItemPacketRewriter1_20_2$$Lambda$5419/0x0000019901bbc818, Packet ID: 37
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: CHUNK_DATA, Type: ChunkType1_18, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.protocol1_20_2to1_20.rewriter.BlockItemPacketRewriter1_20_2$$Lambda$5419/0x0000019901bbc818, Packet ID: 37
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(5117) + length(8) exceeds writerIndex(5122): PooledUnsafeDirectByteBuf(ridx: 5117, widx: 5122, cap: 5122)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:835)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.type.types.LongArrayType.read(LongArrayType.java:39)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.type.types.LongArrayType.read(LongArrayType.java:28)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.type.types.chunk.PaletteType1_18.read(PaletteType1_18.java:51)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.type.types.chunk.ChunkSectionType1_18.read(ChunkSectionType1_18.java:47)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.type.types.chunk.ChunkType1_18.read(ChunkType1_18.java:58)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.type.types.chunk.ChunkType1_18.read(ChunkType1_18.java:36)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:142)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocols.protocol1_20_2to1_20.rewriter.BlockItemPacketRewriter1_20_2.lambda$registerPackets$4(BlockItemPacketRewriter1_20_2.java:96)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocols.protocol1_20_2to1_20.Protocol1_20_2To1_20.transform(Protocol1_20_2To1_20.java:207)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:115)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:248)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.fabric.common.handler.FabricDecodeHandler.decode(FabricDecodeHandler.java:40)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at com.viaversion.fabric.common.handler.FabricDecodeHandler.decode(FabricDecodeHandler.java:17)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[04:27:07] [Netty Client IO #2/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[04:27:07] [Render thread/INFO]: Stopping worker threads

### Bug Description

![image](https://github.com/ViaVersion/ViaFabric/assets/82226339/c73f9afa-d1c7-473f-9413-7070db5baf01)

### Steps to Reproduce

Loggin on 1.20.4 on 1.20/1.20.1 mappings with version of mod and was kicked 

### Expected Behavior

Server connection

### Additional Server Info

Server using velocity and based on 1.16.5 paper

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
1. Without the viavsrsion dump from singleplayer - this issue cannot be checked properly,
2. Please test with viaversion 4.9.3-snapshot as an override mod to see if issues persist from here.

**Comment by swat1x** [comment]
How can I test with another version of ViaVersion if it's not my server. I log in to third-party servers and almost always the first login is accompanied by this error
