### ISSUE TITLE
1.17.1Fabric ViaFabric-0.4.12+53-main is incompatible with ViaBackwards

### ISSUE THREAD

**Issue by Hu1night** [ViaVersion/ViaFabric#304]
### `/viaversion dump` Output

Is Failed to start the minecraft server :(

### Console Error

1.17.1Fab$ java -Xms1024M -Xmx1150M -jar Server-release.jar
[14:57:57] [main/INFO]: Loading Minecraft 1.17.1 with Fabric Loader 0.15.6
[14:57:57] [main/WARN]: Warnings were found!
 - Mod 'ViaBackwards' (viabackwards) 4.10.0-24w05b-SNAPSHOT recommends any version of viarewind, which is missing!
         - You should install any version of viarewind for the optimal experience.
[14:57:57] [main/INFO]: Loading 48 mods:
        - fabric 0.46.1+1.17
           |-- fabric-api-base 0.4.0+cf39a74318
           |-- fabric-api-lookup-api-v1 1.5.0+e821752d18
           |-- fabric-biome-api-v1 3.2.2+cf39a74318
           |-- fabric-blockrenderlayer-v1 1.1.6+cf39a74318
           |-- fabric-command-api-v1 1.1.4+cf39a74318
           |-- fabric-commands-v0 0.2.3+cf39a74318
           |-- fabric-containers-v0 0.1.13+cf39a74318
           |-- fabric-content-registries-v0 0.4.1+3447790d18
           |-- fabric-crash-report-info-v1 0.1.6+cf39a74318
           |-- fabric-dimensions-v1 2.0.15+b556f28c18
           |-- fabric-entity-events-v1 1.4.1+377137cc18
           |-- fabric-events-interaction-v0 0.4.12+e99fbe1218
           |-- fabric-events-lifecycle-v0 0.2.4+cf39a74318
           |-- fabric-game-rule-api-v1 1.0.8+cf39a74318
           |-- fabric-item-api-v1 1.3.0+6617390918
           |-- fabric-item-groups-v0 0.3.2+cf39a74318
           |-- fabric-key-binding-api-v1 1.0.6+2a2bb57318
           |-- fabric-keybindings-v0 0.2.4+cf39a74318
           |-- fabric-lifecycle-events-v1 1.4.6+0392f3a618
           |-- fabric-loot-tables-v1 1.0.5+cf39a74318
           |-- fabric-mining-level-api-v1 1.0.3+cf39a74318
           |-- fabric-mining-levels-v0 0.1.7+cf39a74318
           |-- fabric-models-v0 0.3.1+cf39a74318
           |-- fabric-networking-api-v1 1.0.14+cf39a74318
           |-- fabric-networking-blockentity-v0 0.2.12+cf39a74318
           |-- fabric-networking-v0 0.3.3+cf39a74318
           |-- fabric-object-builder-api-v1 1.11.1+f907116918
           |-- fabric-object-builders-v0 0.7.8+cf39a74318
           |-- fabric-particles-v1 0.2.5+cf39a74318
           |-- fabric-registry-sync-v0 0.8.0+ea29b33318
           |-- fabric-renderer-api-v1 0.4.6+ce16ae5918
           |-- fabric-renderer-indigo 0.4.10+ce16ae5918
           |-- fabric-renderer-registries-v1 3.2.6+cf39a74318
           |-- fabric-rendering-data-attachment-v1 0.1.6+cf39a74318
           |-- fabric-rendering-fluids-v1 0.2.1+cf39a74318
           |-- fabric-rendering-v0 1.1.7+cf39a74318
           |-- fabric-rendering-v1 1.10.1+377137cc18
           |-- fabric-resource-conditions-api-v1 1.0.1+591a0f2118
           |-- fabric-resource-loader-v0 0.4.10+f09604ce18
           |-- fabric-screen-api-v1 1.0.5+cf39a74318
           |-- fabric-screen-handler-api-v1 1.1.9+cf39a74318
           |-- fabric-structure-api-v1 1.2.0+48a9ad8918
           |-- fabric-tag-extensions-v0 1.2.3+cf39a74318
           |-- fabric-textures-v0 1.0.7+cf39a74318
           |-- fabric-tool-attribute-api-v1 1.3.3+3b96517518
           \-- fabric-transfer-api-v1 1.5.4+cf39a74318
        - fabricloader 0.15.6
           \-- mixinextras 0.3.2
        - ferritecore 3.1.0
        - java 21
        - lithium 0.7.5
        - minecraft 1.17.1
        - starlight 1.0.0+fabric.73f6d37
        - viabackwards 4.10.0-24w05b-SNAPSHOT
        - viafabric 0.4.12+55-dev
           |-- cotton-client-commands 1.1.0+1.15.2
           |-- org_yaml_snakeyaml 2.2
           |-- viafabric-mc117 0.4.12+55-dev
           \-- viaversion 4.10.0-23w51b-SNAPSHOT
[14:57:57] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/ubuntu/1.17.1Fab/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[14:57:57] [main/INFO]: Compatibility level set to JAVA_16
[14:57:58] [main/INFO]: Loaded configuration file for Lithium: 87 options available, 0 override(s) found
[14:57:59] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[14:58:08] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin from mod fabric-lifecycle-events-v1::handler$zcf000$fabric-lifecycle-events-v1$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[14:58:09] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[14:58:10] [main/INFO]: Loading translations...
[14:58:10] [Via-Mappingloader-0/INFO]: Using FastUtil Long2ObjectOpenHashMap for block connections
[14:58:10] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'viafabric-mc117'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.6.jar:?]
        at net.minecraft.server.Main.main(Main.java:97) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.6.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [Server-release.jar:1.0.0]
Caused by: java.lang.NoClassDefFoundError: com/viaversion/viaversion/libs/opennbt/tag/io/NBTIO
        at com.viaversion.viabackwards.api.data.VBMappingDataLoader.<clinit>(VBMappingDataLoader.java:39) ~[ViaBackwards-4.10.0-24w05b-SNAPSHOT.jar:?]
        at com.viaversion.viabackwards.api.rewriters.TranslatableRewriter.loadTranslatables(TranslatableRewriter.java:37) ~[ViaBackwards-4.10.0-24w05b-SNAPSHOT.jar:?]
        at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:91) ~[ViaBackwards-4.10.0-24w05b-SNAPSHOT.jar:?]
        at com.viaversion.viabackwards.ViaFabricAddon.run(ViaFabricAddon.java:37) ~[ViaBackwards-4.10.0-24w05b-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at com.viaversion.fabric.mc117.ViaFabric.onInitialize(ViaFabric.java:77) ~[viafabric-mc117-0.4.12+55-dev-5e93b427732688aa.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: com.viaversion.viaversion.libs.opennbt.tag.io.NBTIO
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at com.viaversion.viabackwards.api.data.VBMappingDataLoader.<clinit>(VBMappingDataLoader.java:39) ~[ViaBackwards-4.10.0-24w05b-SNAPSHOT.jar:?]
        at com.viaversion.viabackwards.api.rewriters.TranslatableRewriter.loadTranslatables(TranslatableRewriter.java:37) ~[ViaBackwards-4.10.0-24w05b-SNAPSHOT.jar:?]
        at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:91) ~[ViaBackwards-4.10.0-24w05b-SNAPSHOT.jar:?]
        at com.viaversion.viabackwards.ViaFabricAddon.run(ViaFabricAddon.java:37) ~[ViaBackwards-4.10.0-24w05b-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at com.viaversion.fabric.mc117.ViaFabric.onInitialize(ViaFabric.java:77) ~[viafabric-mc117-0.4.12+55-dev-5e93b427732688aa.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
        ... 7 more

### Bug Description

ViaFabric-0.4.12+55-dev
ViaFabric-0.4.12+54-main
ViaFabric-0.4.12+53-main
is incompatible with ViaBackwards

ViaFabric-0.4.12+53-main is compatible

### Steps to Reproduce

1.A 1.17.1 Fabric Server with 0.4.12+53-main or newer ViaFabric and ViaBackwards
2.Launcher the Server
3.Crash

### Expected Behavior

when using ViaFabric-0.4.12+53-main will not crash

### Additional Server Info

mods:
ferritecore 3.1.0
lithium 0.7.5
starlight 1.0.0+fabric.73f6d37
viabackwards 4.10.0-24w05b-SNAPSHOT
viafabric 0.4.12+55-dev

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Your viafabric, viabackwards and viaversion are not on latest CI builds, please update them and try again.

**Comment by Hu1night** [comment]
I don't know where to find ViaFabric's latest CI builds
But I solved this problem using ViaVersion's latest CI builds

**Comment by FlorianMichael** [comment]
Latest ViaFabric: https://github.com/ViaVersion/ViaFabric/actions/runs/7726594651
