### ISSUE TITLE
versions 0.4.11+43-dev, 0.4.11+42-dev, 0.4.11+41-dev don't work on fabric 1.20.1

### ISSUE THREAD

**Issue by KIRUYXAN** [ViaVersion/ViaFabric#313]
### `/viaversion dump` Output

don't start

### Console Error

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'ViaFabric' (viafabric) 0.4.11+43-dev with any version that is compatible with:
		 - minecraft 1.20.1
More details:
	 - Mod 'ViaFabric' (viafabric) 0.4.11+43-dev requires version 1.8.9, version 1.14.4, version 1.15.2, version 1.16.5, version 1.17.1, version 1.18.2, version 1.19.4 or version 1.20.2-rc.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'Tinfoiled Cotton Client Commands' (cotton-client-commands) 1.1.0+1.15.2 requires any version between 1.14- (inclusive) and 1.16- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'ViaFabric for 1.14' (viafabric-mc114) 0.4.11+43-dev requires version 1.14.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'ViaFabric for 1.15' (viafabric-mc115) 0.4.11+43-dev requires version 1.15.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'ViaFabric for 1.16' (viafabric-mc116) 0.4.11+43-dev requires version 1.16.5 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'ViaFabric for 1.17' (viafabric-mc117) 0.4.11+43-dev requires version 1.17.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'ViaFabric for 1.18' (viafabric-mc118) 0.4.11+43-dev requires version 1.18.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'ViaFabric for 1.19' (viafabric-mc119) 0.4.11+43-dev requires version 1.19.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'ViaFabric for 1.20' (viafabric-mc120) 0.4.11+43-dev requires version 1.20.2-rc.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Bug Description

When I star minecraft I have this error

### Steps to Reproduce

Start Fabric 1.20.1 have error

### Expected Behavior

Satrt minecraft

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
1.20.1 is unsupported.

**Comment by KIRUYXAN** [comment]
And how did it start with version 0.4.10+40-main then
