### ISSUE TITLE
ViaFabric on 1.20.6 can't work

### ISSUE THREAD

**Issue by 3306780700** [ViaVersion/ViaFabric#334]
### `/viaversion dump` Output

none

### Console Error

I installed ViaFabric on the minecraft server (1.20.6) but it didn't work when I started and when I uninstalled the ViaFabric server side worked fine.

### Bug Description

[main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'viafabric-mc1206'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
        at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-launch.jar:1.0.1]
Caused by: java.lang.IncompatibleClassChangeError: class com.viaversion.fabric.common.commands.subs.LeakDetectSubCommand has interface com.viaversion.viaversion.api.command.ViaSubCommand as super class
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at com.viaversion.fabric.mc1206.commands.VFCommandHandler.<init>(VFCommandHandler.java:33) ~[viafabric-mc1206-0.4.14+70-main-ab2d9b455775e43b.jar:?]
        at com.viaversion.fabric.mc1206.ViaFabric.onInitialize(ViaFabric.java:81) ~[viafabric-mc1206-0.4.14+70-main-ab2d9b455775e43b.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
        ... 7 more

### Steps to Reproduce

1.Put it into ViaFabric
2.Start Minecraft Server 1.20.6
3.Error

### Expected Behavior

Start the server normally and the Via mods is working normally.

### Additional Server Info

In addition to Via mods, there are easyauth,fabric-api,geyser,polymer

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by 3306780700** [comment]
But, they're installed.

**Comment by Kichura** [comment]
can't reproduce this on my end tho.

**Comment by 3306780700** [comment]
VNC remote connection to my server to try?

**Comment by Kichura** [comment]
I do not accept VNC requests, though i do wish to request for your mods list to be seen albeit using `dir/w` *(windows)* or `ls` *(unix)*.

**Comment by 3306780700** [comment]
FabricAPI ViaFabric ViaVersion ViaBackwards ViaRewind Easyauth Geyser Polymer

**Comment by Kichura** [comment]
> FabricAPI ViaFabric ViaVersion ViaBackwards ViaRewind Easyauth Geyser Polymer

Do the following then:

1. Update ViaFabric to 0.4.14+70-main,
2. Update ViaBackwards to 4.10.2,
3. ViaRewind is broken at the moment as 1.19.0 and older clients can't join 1.20.4 / 1.20.6 fabric servers,
4. Update Geyser to latest fabric build but also include floodgate in your mods folder.

**Comment by 3306780700** [comment]
![image](https://github.com/ViaVersion/ViaFabric/assets/160383459/57a507c5-603e-4bc9-afdc-7b901d0dae53)

**Comment by 3306780700** [comment]
OK, I'm going to try it.

**Comment by 3306780700** [comment]
No, the error is the same as before.

**Comment by 3306780700** [comment]
![image](https://github.com/ViaVersion/ViaFabric/assets/160383459/825a99a2-a144-41d9-9116-d32f0bc99aac)

**Comment by Kichura** [comment]
Don't use viaversion 5.0.0-snapshot with viabackwards 4.10.2 as that is incompatible,
Please exclude that from your mods folder as 70-main already has viaversion 4.10.2 bundled.

**Comment by 3306780700** [comment]
Thanks! It worked fine.
