### ISSUE TITLE
Mod 'ViaFabric for 1.xx' requires version 1.xx of 'Minecraft' but only the wrong version is present: 1.21!

### ISSUE THREAD

**Issue by HatTrkPatrk** [ViaVersion/ViaFabric#356]
### `/viaversion dump` Output

https://dump.viaversion.com/i-cant-start-the-server-so-no-i-cant-run-this-command

### Console Error

[04:15:26] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.15.11
[04:15:26] [ForkJoinPool-1-worker-1/WARN]: The mod "betterstats" contains invalid entries in its mod json:
- Unsupported root entry "" at line 26 column 4
- Unsupported root entry "" at line 26 column 92
- Unsupported root entry "" at line 28 column 4
- Unsupported root entry "" at line 28 column 24
[04:15:26] [ForkJoinPool-1-worker-1/WARN]: The mod "tcdcommons" contains invalid entries in its mod json:
- Unsupported root entry "" at line 27 column 4
- Unsupported root entry "" at line 27 column 198
- Unsupported root entry "" at line 29 column 4
- Unsupported root entry "" at line 29 column 24
[04:15:26] [ForkJoinPool-1-worker-1/WARN]: Mod wither_spawn_fix uses the version MC1.21-1.0.0 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'MC1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[04:15:26] [ForkJoinPool-1-worker-1/WARN]: Mod mr_stonecutter_damage uses the version 1-mcmeta-45-48_1.21 which isn't compatible with Loader's extended semantic version format (Invalid prerelease string 'mcmeta-45-48_1.21'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[04:15:26] [main/WARN]: Mod resolution failed
[04:15:26] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE forgeconfigapiport 21.0.5 {depends fabricloader @ [>=0.16.0]}, ROOT_FORCELOAD_SINGLE forgeconfigapiport 21.0.5]
[04:15:26] [main/INFO]: Reason: [HARD_DEP forgeconfigapiport 21.0.5 {depends fabricloader @ [>=0.16.0]}, HARD_DEP viafabric-mc1144 0.4.14+74-main {depends minecraft @ [1.14.4]}, HARD_DEP viafabric-mc1152 0.4.14+74-main {depends minecraft @ [1.15.2]}, HARD_DEP viafabric-mc1165 0.4.14+74-main {depends minecraft @ [1.16.5]}, HARD_DEP viafabric-mc1171 0.4.14+74-main {depends minecraft @ [1.17.1]}, HARD_DEP viafabric-mc1182 0.4.14+74-main {depends minecraft @ [1.18.2]}, HARD_DEP viafabric-mc1194 0.4.14+74-main {depends minecraft @ [1.19.4]}, HARD_DEP viafabric-mc1201 0.4.14+74-main {depends minecraft @ [1.20.1]}, HARD_DEP viafabric-mc1204 0.4.14+74-main {depends minecraft @ [1.20.3 || 1.20.4]}, HARD_DEP viafabric-mc1206 0.4.14+74-main {depends minecraft @ [1.20.5 || 1.20.6]}]
[04:15:26] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-model-loading-api-v1, fabric-keybindings-v0, jackfredlib-toasts, fabric-client-tags-api-v1, fabric-screen-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, cotton-client-commands, jackfredlib-gps, fabric-sound-api-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-key-binding-api-v1]
[04:15:26] [main/INFO]: Fix: add [], remove [], replace [[fabricloader 0.15.11] -> add:fabricloader 0.16.0 ([[0.16.0,∞)])]
[04:15:26] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Fabric Loader' (fabricloader) 0.15.11 with version 0.16.0 or later.
More details:
	 - Mod 'Forge Config API Port' (forgeconfigapiport) 21.0.5 requires version 0.16.0 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.15.11!
	 - Mod 'ViaFabric for 1.14' (viafabric-mc1144) 0.4.14+74-main requires version 1.14.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	 - Mod 'ViaFabric for 1.15' (viafabric-mc1152) 0.4.14+74-main requires version 1.15.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	 - Mod 'ViaFabric for 1.16' (viafabric-mc1165) 0.4.14+74-main requires version 1.16.5 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	 - Mod 'ViaFabric for 1.17' (viafabric-mc1171) 0.4.14+74-main requires version 1.17.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	 - Mod 'ViaFabric for 1.18' (viafabric-mc1182) 0.4.14+74-main requires version 1.18.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	 - Mod 'ViaFabric for 1.19' (viafabric-mc1194) 0.4.14+74-main requires version 1.19.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	 - Mod 'ViaFabric for 1.20.1' (viafabric-mc1201) 0.4.14+74-main requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	 - Mod 'ViaFabric for 1.20.4' (viafabric-mc1204) 0.4.14+74-main requires version 1.20.3 or version 1.20.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	 - Mod 'ViaFabric for 1.20.5/6' (viafabric-mc1206) 0.4.14+74-main requires version 1.20.5 or version 1.20.6 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]

### Bug Description

Obviously I don't have every version of Minecraft installed since 1.14, I'm running a 1.21 server. But for some reason, ViaFabric seems to expect every version at the same time?

### Steps to Reproduce

1. Create a 1.21 Fabric server with ViaFabric in the mods folder
2. Attempt to start the server

### Expected Behavior

...

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [ ] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Not a viafabric-related bug as it says betterstats instead.
