### ISSUE TITLE
1.21.3 Incompatibility

### ISSUE THREAD

**Issue by Kyberilium08** [ViaVersion/ViaFabric#380]
### `/viaversion dump` Output

-none

### Console Error

```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'ViaFabric' (viafabric) 0.4.15+84-main with version 0.4.10 or later that is compatible with:
		 - minecraft 1.21.3
More details:
	 - Mod 'ViaFabric' (viafabric) 0.4.15+84-main requires version 1.14.4, version 1.15.2, version 1.16.4, version 1.16.5, version 1.17.1, version 1.18.2, version 1.19.4, version 1.20, version 1.20.1, version 1.20.3, version 1.20.4, version 1.20.5, version 1.20.6, version 1.21 or version 1.21.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.3!
	 - Mod 'ViaFabric for 1.14' (viafabric-mc1144) 0.4.15+84-main requires version 1.14.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.3!
	 - Mod 'ViaFabric for 1.15' (viafabric-mc1152) 0.4.15+84-main requires version 1.15.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.3!
	 - Mod 'ViaFabric for 1.16' (viafabric-mc1165) 0.4.15+84-main requires version 1.16.4 or version 1.16.5 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.3!
	 - Mod 'ViaFabric for 1.17' (viafabric-mc1171) 0.4.15+84-main requires version 1.17.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.3!
	 - Mod 'ViaFabric for 1.18' (viafabric-mc1182) 0.4.15+84-main requires version 1.18.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.3!
	 - Mod 'ViaFabric for 1.19' (viafabric-mc1194) 0.4.15+84-main requires version 1.19.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.3!
	 - Mod 'ViaFabric for 1.20.1' (viafabric-mc1201) 0.4.15+84-main requires version 1.20 or version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.3!
	 - Mod 'ViaFabric for 1.20.4' (viafabric-mc1204) 0.4.15+84-main requires version 1.20.3 or version 1.20.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.3!
	 - Mod 'ViaFabric for 1.20.5/6' (viafabric-mc1206) 0.4.15+84-main requires version 1.20.5 or version 1.20.6 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.3!
	 - Mod 'ViaFabric for 1.21.1' (viafabric-mc1211) 0.4.15+84-main requires version 1.21 or version 1.21.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.3!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)

```

### Bug Description

Mod incompatible with the most recent Minecraft Version 1.21.3

### Steps to Reproduce

Install 1.21.3 server with ViaFabric-0.4.15+84-main. The server will not launch and will give you the error message.

### Expected Behavior

The server is supposed to start.

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
1.21.2/3 support has not been finalized yet, The 1.21.1 -> 1.21.2/3 transition will begin once ViaVersion 5.1.x is ready.
