### ISSUE TITLE
Incompatibility with 1.21.1

### ISSUE THREAD

**Issue by CozzyBro2** [ViaVersion/ViaFabric#386]
### `/viaversion dump` Output

N/A

### Console Error

```
[22:08:14] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.9
[22:08:14] [main/WARN]: Mod resolution failed
[22:08:14] [main/INFO]: Immediate reason: [HARD_DEP viabackwards 5.1.1 {depends viafabric @ [>=0.4.14]}, HARD_DEP_INCOMPATIBLE_PRESELECTED viafabric 0.4.16+695-main {depends minecraft @ [1.14.4 || 1.15.2 || 1.16.4 || 1.16.5 || 1.17.1 || 1.18.2 || 1.19.4 || 1.20 || 1.20.1 || 1.20.3 || 1.20.4 || 1.20.5 || 1.20.6 || 1.21.2 || 1.21.3]}, ROOT_FORCELOAD_SINGLE viabackwards 5.1.1]
[22:08:14] [main/INFO]: Reason: [HARD_DEP viafabric 0.4.16+695-main {depends minecraft @ [1.14.4 || 1.15.2 || 1.16.4 || 1.16.5 || 1.17.1 || 1.18.2 || 1.19.4 || 1.20 || 1.20.1 || 1.20.3 || 1.20.4 || 1.20.5 || 1.20.6 || 1.21.2 || 1.21.3]}, HARD_DEP viafabric-mc1144 0.4.16+695-main {depends minecraft @ [1.14.4]}, HARD_DEP viafabric-mc1152 0.4.16+695-main {depends minecraft @ [1.15.2]}, HARD_DEP viafabric-mc1165 0.4.16+695-main {depends minecraft @ [1.16.4 || 1.16.5]}, HARD_DEP viafabric-mc1171 0.4.16+695-main {depends minecraft @ [1.17.1]}, HARD_DEP viafabric-mc1182 0.4.16+695-main {depends minecraft @ [1.18.2]}, HARD_DEP viafabric-mc1194 0.4.16+695-main {depends minecraft @ [1.19.4]}, HARD_DEP viafabric-mc1201 0.4.16+695-main {depends minecraft @ [1.20 || 1.20.1]}, HARD_DEP viafabric-mc1204 0.4.16+695-main {depends minecraft @ [1.20.3 || 1.20.4]}, HARD_DEP viafabric-mc1206 0.4.16+695-main {depends minecraft @ [1.20.5 || 1.20.6]}, HARD_DEP viafabric-mc1213 0.4.16+695-main {depends minecraft @ [1.21.2 || 1.21.3]}]
[22:08:14] [main/INFO]: SERVER environment disabled: [fabric-model-loading-api-v1, fabric-renderer-api-v1, fabric-keybindings-v0, viafabricplus, fabric-client-tags-api-v1, fabric-screen-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, cotton-client-commands, fabric-rendering-v0, fabric-sound-api-v1, fabric-rendering-v1, fabric-key-binding-api-v1]
[22:08:14] [main/INFO]: Fix: add [], remove [], replace [[viafabric 0.4.16+695-main] -> add:viafabric 0.4.14 ([[0.4.14,∞)])]
[22:08:14] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
         - Replace mod 'ViaFabric' (viafabric) 0.4.16+695-main with version 0.4.14 or later that is compatible with:
                 - minecraft 1.21.1
More details:
         - Mod 'ViaFabric' (viafabric) 0.4.16+695-main requires version 1.14.4, version 1.15.2, version 1.16.4, version 1.16.5, version 1.17.1, version 1.18.2, version 1.19.4, version 1.20, version 1.20.1, version 1.20.3, version 1.20.4, version 1.20.5, version 1.20.6, version 1.21.2 or version 1.21.3 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
         - Mod 'ViaFabric for 1.14' (viafabric-mc1144) 0.4.16+695-main requires version 1.14.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
         - Mod 'ViaFabric for 1.15' (viafabric-mc1152) 0.4.16+695-main requires version 1.15.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
         - Mod 'ViaFabric for 1.16' (viafabric-mc1165) 0.4.16+695-main requires version 1.16.4 or version 1.16.5 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
         - Mod 'ViaFabric for 1.17' (viafabric-mc1171) 0.4.16+695-main requires version 1.17.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
         - Mod 'ViaFabric for 1.18' (viafabric-mc1182) 0.4.16+695-main requires version 1.18.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
         - Mod 'ViaFabric for 1.19' (viafabric-mc1194) 0.4.16+695-main requires version 1.19.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
         - Mod 'ViaFabric for 1.20.1' (viafabric-mc1201) 0.4.16+695-main requires version 1.20 or version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
         - Mod 'ViaFabric for 1.20.4' (viafabric-mc1204) 0.4.16+695-main requires version 1.20.3 or version 1.20.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
         - Mod 'ViaFabric for 1.20.5/6' (viafabric-mc1206) 0.4.16+695-main requires version 1.20.5 or version 1.20.6 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
         - Mod 'ViaFabric for 1.21.3' (viafabric-mc1213) 0.4.16+695-main requires version 1.21.2 or version 1.21.3 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
```

### Bug Description

Mod does not support mc 1.21.1
---
Looking at past github issues, it appears the mod once did. [logfile of this issue shows support for 1.21.1. ](https://github.com/ViaVersion/ViaFabric/issues/380) no such line is found in my logs
However, no version i've been able to find currently works with 1.21.1. I am locked on 1.21.1 for the moment as not all of my server-side mods have support
(I am currently using Actions' Artifiact of version `(viafabric-mc1213) 0.4.16+695`)

### Steps to Reproduce

Download `(viafabric-mc1213) 0.4.16+695`
Run a fabric 1.21.1 server

### Expected Behavior

Server should start properly

### Additional Server Info

Server is running behind itzg/minecraft-server
No conflicting mods are used

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
The viafabric copy you have no longer supports 1.21.1. Downgrade to 0.4.15+84-main then update viaversion and viabackwards from the [CI website](https://ci.viaversion.com).

**Comment by PukPukov** [comment]
Supporting 1.x.latest (i.e. latest "patch") while mojang releases major updates bumping only patch number is not productive (diff and breaking changes between 20.4 and 20.6 are much bigger than between 20.6 and 21.1). The best approach would be supporting most popular versions, and 21.1 is certainly among them, while 20.6 or even 17.1 are not. I think atm, latest and 21.1 are the most popular versions in the "modern epoch".

**Comment by Kichura** [comment]
> Supporting 1.x.latest (i.e. latest "patch") while mojang releases major updates bumping only patch number is not productive (diff and breaking changes between 20.4 and 20.6 are much bigger than between 20.6 and 21.1). The best approach would be supporting most popular versions, and 21.1 is certainly among them, while 20.6 or even 17.1 are not. I think atm, latest and 21.1 are the most popular versions in the "modern epoch".

This is planned in [this issue](https://github.com/ViaVersion/ViaFabric/issues/408) however EnZa did attempt this with replaymod preprocessor but it just didn't work for him, which is why i marked that as "help wanted".
