### ISSUE TITLE
NPE at protocoldetectionhandler

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaFabric#80]
[19:03:13] [Netty Client IO #0/ERROR]: Unexpectedly disconnected from server!
java.lang.NullPointerException: Cannot invoke "us.myles.ViaVersion.api.Pair.getKey()" because "it" is null
	at com.github.creeper123123321.viafabric.handler.clientside.ProtocolDetectionHandler.lambda$drainQueue$2(ProtocolDetectionHandler.java:95) ~[ViaFabric-0.2.16-SNAPSHOT+build-608.1-mc-1.16.jar:?]
	at java.util.ArrayDeque.forEach(ArrayDeque.java:888) ~[?:?]
	at

**Comment by creeper123123321** [comment]
leak here: https://github.com/ViaVersion/ViaFabric/blob/c25b09355ce2e70db1123d72f71f0a41ed97a2d7/src/main/java/com/github/creeper123123321/viafabric/handler/clientside/ProtocolDetectionHandler.java#L103

**Comment by creeper123123321** [comment]
Wrong executor https://github.com/ViaVersion/ViaFabric/blob/mc-1.16/src/main/java/com/github/creeper123123321/viafabric/handler/clientside/ProtocolDetectionHandler.java#L60

**Comment by creeper123123321** [comment]
> Wrong executor https://github.com/ViaVersion/ViaFabric/blob/mc-1.16/src/main/java/com/github/creeper123123321/viafabric/handler/clientside/ProtocolDetectionHandler.java#L60

Channel pipeline seems to be thread safe
